version: '3'

services:
  app:
    build: https://github.com/findlayfeng/aria2-ariang-docker.git#del_ARIA2RPCPORT
    restart: always
    command:
      - --conf-path=/aria2/conf/aria2.conf
      - --listen-port=${LISTENPORT:-51413}
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - RPC_SECRET=${RPC_SECRET:-secret}
    volumes:
      - ./aria2.conf:/aria2/conf-copy/aria2.conf:ro
      - config:/aria2/conf
      - ${ARIA2_DOWNLOAD:-./download}:/aria2/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.aria2.rule=Host(`${ARIA2_DOMAIN}`)
      - traefik.http.routers.aria2.entrypoints=${ARIA2_ENTRYPOINTS:-}
      - traefik.http.services.aria2-service.loadbalancer.server.port=8080
    ports:
      - ${LISTENPORT:-51413}:${LISTENPORT:-51413}
      - ${LISTENPORT:-51413}:${LISTENPORT:-51413}/udp
    networks:
      - proxy

volumes:
  config:

networks:
  proxy:
    external: true
