services:
  volume-init:
    image: alpine
    restart: on-failure:3
    command: mkdir -p /opt/scrutiny/influxdb /opt/scrutiny/config
    volumes:
      - scrutiny:/opt/scrutiny

  mysql:
    image: mysql:lts
    restart: always
    environment:
      - TZ=${TZ:-UTC}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-}
      - MYSQL_RANDOM_ROOT_PASSWORD=${MYSQL_RANDOM_ROOT_PASSWORD:-}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-aio}
      - MYSQL_USER=${MYSQL_USER:-${MYSQL_DATABASE:-aio}}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-}
    networks:
      default:
        ipv4_address: 169.254.4.128
        aliases:
          - mysql
    volumes:
      - mysql_data:/var/lib/mysql

  pgsql:
    image: postgres:17-alpine
    restart: always
    shm_size: 128mb
    environment:
      - TZ=${TZ:-UTC}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB:-aio}
      - POSTGRES_USER=${POSTGRES_USER:-${POSTGRES_DB:-aio}}

    volumes:
      - pgsql_data:/var/lib/postgresql/data

    networks:
      default:
        ipv4_address: 169.254.4.130

  redis:
    image: redis:alpine
    restart: always
    networks:
      default:
        ipv4_address: 169.254.4.129

  scrutiny:
    extends:
      file: ../override.yml
      service: x-scrutiny
    restart: always
    depends_on:
      - volume-init
    image: ghcr.io/analogj/scrutiny:latest
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    labels:
      - traefik.enable=true
      - traefik.http.services.scrutiny.loadbalancer.server.port=8080
    volumes:
      - /run/udev:/run/udev:ro
      - type: volume
        source: scrutiny
        volume:
          subpath: config
        target: /opt/scrutiny/config
      - type: volume
        source: scrutiny
        volume:
          subpath: influxdb
        target: /opt/scrutiny/influxdb
    networks:
      default:
        ipv4_address: 169.254.4.131

volumes:
  pgsql_data:
  mysql_data:
  scrutiny:

networks:
  default:
    internal: true
    driver: bridge
    name: internal
    ipam:
      driver: default
      config:
        - subnet: 169.254.4.0/24
          ip_range: 169.254.4.0/25
