version: '3'

services:
  app:
    image: gitlab/gitlab-ce:16.4.1-ce.0
    restart: always
    hostname: "${GITLAB_DOMAIN}"
    environment:
      TZ: ${TZ:-America/New_York}
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://GITLAB_DOMAIN'
    shm_size: '256m'
    volumes:
      - data:/var/opt/gitlab
      - config:/etc/gitlab
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitlab.rule=Host(`${GITLAB_DOMAIN}`)
      - traefik.http.routers.gitlab.entrypoints=${GITLAB_ENTRYPOINTS:-}
      - traefik.http.routers.gitlab.service=gitlab-service
      - traefik.http.services.gitlab-service.loadbalancer.server.port=80
      - traefik.tcp.routers.gitlab-ssh.rule=HostSNI(`*`)
      - traefik.tcp.routers.gitlab-ssh.entrypoints=${GITLAB_SSH_ENTRYPOINTS:-gitlab-ssh}
      - traefik.tcp.routers.gitlab-ssh.service=gitlab-ssh-service
      - traefik.tcp.services.gitlab-ssh-service.loadbalancer.server.port=22
    networks:
      - proxy

volumes:
  config:
  data:

networks:
  proxy:
    external: true
