version: '3'

services:
  app:
    image: quay.io/minio/minio
    restart: always
    command:
      - server
      - /data
      - --console-address
      - ":9090"
    environment:
      - TZ=${TZ:-America/New_York}
    volumes:
      - data:/data
    labels:
      - traefik.http.routers.minio.rule=Host(`${MINIO_DOMAIN}`)
      - traefik.http.routers.minio.service=minio-service
      - traefik.http.services.minio-service.loadbalancer.server.port=9000
      - traefik.http.routers.minio-console.rule=Host(`${MINIO_CONSOLE_DOMAIN}`)
      - traefik.http.routers.minio-console.service=minio-console-service
      - traefik.http.services.minio-console-service.loadbalancer.server.port=9090
    networks:
      - proxy
volumes:
  data:

networks:
  proxy:
    external: true
